default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Root@123
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: getting_started_blog_development

test:
  <<: *default
  database: getting_started_blog_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: getting_started_blog_production
  username: getting_started_blog
  password: <%= ENV['GETTING_STARTED_BLOG_DATABASE_PASSWORD'] %>
